### ISSUE TITLE
docker 报hlink没有权限，试试使用sudo执行

### ISSUE THREAD

**Issue by KrDw9ec4** [likun7981/hlink#181]
docker部署，报hlink没有权限，试试使用sudo执行，实在想不明白 docker 部署我该怎么用 sudo 执行这个命令，查遍了也没发现相关的 issues……

docker compose 文件：

```yaml
services:
  docker:
    image: likun7981/hlink:latest
    restart: on-failure
    ports:
      # 这个端口映射
      - 9090:9090
    volumes:
      # 这个表示存储空间映射
      - /mnt/tiplus/animes:/animes
      - /home/krdw/docker/data/hlink:/config
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - HLINK_HOME=/config
```

运行错误日志：

```log
[24/05/04 20:17:30]  WARN  hlink没有权限
[24/05/04 20:17:30]  WARN   试试使用sudo执行: sudo hlink xxxx
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:32
                throw new HLinkError(errorCode, `${chalk.gray(getDirBasePath(source, sourceFile))} ${chalk.cyan('>')} ${getDirBasePath(dest, path.join(originalDestPath, path.basename(sourceFile)))}`);
                      ^

HLinkError
    at link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:32:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 1)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  isHlinkError: true,
  code: 'NotPermitted',
  filepath: '\x1B[90mcollect/GIRLS BAND CRY/[Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 02 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv\x1B[39m \x1B[36m>\x1B[39m collect/GIRLS BAND CRY/[Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 02 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv',
  reason: undefined,
  ignore: false
}

Node.js v18.16.0

[24/05/04 20:17:30]  ERROR  任务执行出错，已终止
```

目录都是当前用户所有，真不太清楚哪里有权限问题……
